### ISSUE TITLE
Improve discoverability of helia-mfs

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia-mfs#3]
This issue is intended to track any actions to help improve the discoverability of this repo.

- [x] Add a reference to it in the Helia readme: https://github.com/ipfs/helia
- [x] Update the migration guide: https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS#mfs
- [x] Update the triage links for the Helia repos: https://www.notion.so/pl-strflt/Helia-Working-Group-WG-70bbeced695249808940bf7a37992f71?pvs=4#fc01652047744b0d889504a5c77b3f22

**Comment by achingbrain** [comment]
Closing as all tasks are complete.
