### ISSUE TITLE
There is no addDirectory method / writeBytes and mkdir return a Promise<void>. How to use?

### ISSUE THREAD

**Issue by BjrInt** [ipfs/helia-mfs#5]
According to the [documentation example](https://ipfs.github.io/helia-mfs/interfaces/MFS.html#mkdir), creating an empty directory is done using the `addDirectory` method, that should return a cid : 
```js
const directoryCid = await fs.addDirectory()

const updatedCid = await fs.mkdir(directoryCid, 'new-dir')

console.info(updatedCid)
``` 

However this method is not exported by the MFS package. 

Similarly the [writeBytes example](https://ipfs.github.io/helia-mfs/interfaces/MFS.html#writeBytes) is using another method called `addBytes` (which is not exported either).

Both `mkdir` and `writeBytes` have `Promise<void>` as a return value, when they should return a CID according to the examples... 
Am I doing something wrong?

**Comment by BjrInt** [comment]
Also opened #4 but this PR might not be addressing the underlying issue.

**Comment by BjrInt** [comment]
Thanks for the exhaustive answer. 

I am building an UI to add files and directories to a Helia node and so far the only solution I have found to get the root CID of a directory is to call `fs.root.toString()` (where fs is an mfs instance). Is there an other way to do this?

Here is the code for context: 
```js
for(let file of files) {
  const content = await file.arrayBuffer()

  if(!file.webkitRelativePath) 
    await fs.writeBytes(new Uint8Array(content), `/${file.name}`)
  else{
    // Remove the root directory from the path
    const splittedName = file.webkitRelativePath.split('/').slice(1)

    if(splittedName.length > 1) {
      for(let i=0; i<splittedName.length-1; i++) {
        const dirName = splittedName.slice(0, i+1).join('/')
        try{
          await fs.stat(`/${dirName}`)
        }
        catch(err) {
          console.log(`Creating new directory: ${dirName}`)
          await fs.mkdir(`/${dirName}`)
        }
      }
    }

    await fs.writeBytes(new Uint8Array(content), `/${splittedName.join('/')}`)
  }
}

console.log(fs.root.toString())
```

**Comment by achingbrain** [comment]
You can stat the root path: `fs.stat('/')`, it returns a [UnixFSStats](https://ipfs.github.io/helia-unixfs/interfaces/index.UnixFSStats.html) which includes the CID - for more info see https://ipfs.github.io/helia-mfs/interfaces/MFS.html#stat

**Comment by BjrInt** [comment]
Thank you very much, closing this as it is now irrelevant!
