### ISSUE TITLE
README improvements to explain what this repo is for and why someone should consider using it

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia-mfs#8]
The big thing is that someone comes to the project, they aren't provided any explanation for why they should use this project.  When I write data to mutable file system, where are the bytes written?

There is a separate side of needing to improve discoverability: https://github.com/ipfs/helia-mfs/issues/3

**Comment by achingbrain** [comment]
The READMEs are in better shape now, any PRs should update the `@packageDocumentation` tag in the [index.ts](https://github.com/ipfs/helia/blob/main/packages/mfs/src/index.ts#L1-L30) file - this will get copied to the README when docs are built prior to publishing.
